/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subscription_service;

import com.rabbitmq.client.ConnectionFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        ConnectionFactory factory = new ConnectionFactory();

        System.out.println("Should be connected");
    }
}
